name: Build & Translate Cookie Data

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'excel-to-json.py'
      - 'json_translator_rewrite.py'
      - 'translation_key.json'
      - '**.xlsx'
      - '.github/workflows/build-translate.yml'
      - 'requirements.txt'

permissions:
  contents: read

concurrency:
  group: build-translate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas openpyxl python-dateutil
          fi

      # Step 1: Excel -> converted_cookie_data.json
      - name: Convert Excel to converted_cookie_data.json
        run: |
          python excel-to-json.py
          test -f converted_cookie_data.json || { echo "::error::converted_cookie_data.json was not created"; exit 1; }

      # Step 2: Translate JSON into all locales (pretty + minified)
      - name: Generate localized JSONs
        run: |
          python json_translator_rewrite.py --translate_keys
          test -d out && [ "$(ls -A out)" ] || { echo "::error::No files in out/"; exit 1; }
          test -d minified && [ "$(ls -A minified)" ] || { echo "::error::No files in minified/"; exit 1; }

      # Step 3: Upload artifacts
      - name: Upload pretty JSONs
        uses: actions/upload-artifact@v4
        with:
          name: cookie-jsons-pretty
          path: out/
          if-no-files-found: error

      - name: Upload minified JSONs
        uses: actions/upload-artifact@v4
        with:
          name: cookie-jsons-minified
          path: minified/
          if-no-files-found: error

      # Optional: Inspect outputs for debugging
      - name: Show sample outputs
        if: always()
        run: |
          echo "== out/ sample =="
          ls -la out | head -n 20 || true
          echo "== minified/ sample =="
          ls -la minified | head -n 20 || true

      # OPTIONAL: commit generated files back to repo (uncomment to enable)
      # - name: Commit generated files
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "chore: update localized cookie JSONs"
      #     file_pattern: out/** minified/**
      #     branch: ${{ github.ref_name }}
