name: Build & Translate Cookie Data

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'excel-to-json.py'
      - 'json_translator_rewrite.py'
      - 'translation_key.json'
      - '**.xlsx'
      - '.github/workflows/build-translate.yml'
      - 'requirements.txt'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas openpyxl
          fi

      - name: Convert all Excel files to grouped JSON
        run: |
          python excel-to-json.py

      - name: Translate all grouped JSONs
        run: |
          python json_translator_rewrite.py --translate_keys

      - name: Upload pretty JSONs
        uses: actions/upload-artifact@v4
        with:
          name: cookie-jsons-pretty
          path: out
          if-no-files-found: error

      - name: Upload minified JSONs
        uses: actions/upload-artifact@v4
        with:
          name: cookie-jsons-minified
          path: minified
          if-no-files-found: error
